export const SLICE_NAME = 'book';

export const FETCH_WORDS_FAILURE = `${SLICE_NAME}/FETCH_WORDS_FAILURE`;
export const FETCH_WORDS_SUCCESS = `${SLICE_NAME}/FETCH_WORDS_SUCCESS`;
export const UPDATE_CURRENT_GROUP = `${SLICE_NAME}/UPDATE_CURRENT_GROUP`;
export const UPDATE_CURRENT_PAGE = `${SLICE_NAME}/UPDATE_CURRENT_PAGE`;
export const SHOW_LOADER = `${SLICE_NAME}/SHOW_LOADER`;
export const HIDE_LOADER = `${SLICE_NAME}/HIDE_LOADER`;
