export const SLICE_NAME = 'kit';

export const RANDOM_WORDS = `${SLICE_NAME}/RANDOM_WORDS`;
export const CURRENT_WORD = `${SLICE_NAME}/CURRENT_WORD`;
export const WORD_INCREMENT = `${SLICE_NAME}/WORD_INCREMENT`;
export const CHAR_INCREMENT = `${SLICE_NAME}/CHAR_INCREMENT`;
