export const SLICE_NAME = 'app';

export const UPDATE_CURRENT_LANGUAGE = `${SLICE_NAME}/UPDATE_CURRENT_LANGUAGE`;
export const REGISTER_SUCCESS = `${SLICE_NAME}/REGISTER_SUCCESS`;
export const REGISTER_FAILURE = `${SLICE_NAME}/REGISTER_FAILURE`;
export const LOGIN_SUCCESS = `${SLICE_NAME}/LOGIN_SUCCESS`;
export const LOGIN_FAILURE = `${SLICE_NAME}/LOGIN_FAILURE`;
export const LOGOUT_SUCCESS = `${SLICE_NAME}/LOGOUT_SUCCESS`;
