export const SLICE_NAME = 'app';

export const UPDATE_CURRENT_LANGUAGE = `${SLICE_NAME}/UPDATE_CURRENT_LANGUAGE`;
export const REGISTER_SUCCESS = `${SLICE_NAME}/REGISTER_SUCCESS`;
export const UPDATE_ERROR_MESSAGE = `${SLICE_NAME}/UPDATE_ERROR_MESSAGE`;
export const LOGIN_SUCCESS = `${SLICE_NAME}/LOGIN_SUCCESS`;
export const UPDATE_USER_ERROR_MESSAGE = `${SLICE_NAME}/UPDATE_USER_ERROR_MESSAGE`;
export const LOGOUT_SUCCESS = `${SLICE_NAME}/LOGOUT_SUCCESS`;
export const MENU_TOGGLE = `${SLICE_NAME}/MENU_TOGGLE`;
export const SAVE_USER_AUTH_DATA = `${SLICE_NAME}/SAVE_USER_AUTH_DATA`;
export const CLEAR_ERROR_MESSAGE = `${SLICE_NAME}/CLEAR_ERROR_MESSAGE`;
export const SHOW_LOADER = `${SLICE_NAME}/SHOW_LOADER`;
export const HIDE_LOADER = `${SLICE_NAME}/HIDE_LOADER`;
